# Generated by Django 5.0.3 on 2024-03-26 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_alter_user_last_name_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='passw',
        ),
    ]
